# -*- coding: utf-8 -*-
"""VRSU_LAB2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HzIK6TUUCYOmUbD-QKE4NEFNhL7e6p7d
"""

#openCV reads images in BGR
#matplotlib expects RGB

#Image segmentation

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

uploaded = files.upload()

img_path = list(uploaded.keys())[0]

#reading the image in grayscale
img = cv2.imread(img_path, 0)
img_1 = cv2.imread(img_path)
img_rgb =   cv2.cvtColor(img_1, cv2.COLOR_BGR2RGB)

if img is None:
  raise ValueError("Error Loading the image")

#threshold(src, thresh, maxval, type)
threshold_value, binary_img = cv2.threshold(img, 100, 255, cv2.THRESH_BINARY)

print("Optimal threshold value:", threshold_value)
#display results
plt.figure(figsize=(10,4))
plt.subplot(1,2,1)
plt.title("original Image")
plt.imshow(img_rgb)
plt.axis("off")

plt.subplot(1,2,2)
plt.title("Histogram")
plt.hist(img.ravel(), 256)
plt.xlabel("Pixel Inensity")
plt.ylabel("Frequency")

plt.subplot(1,3,3)
plt.title("Otsu Binarized Image")
plt.imshow(binary_img, cmap="gray")
plt.axis("off")
plt.show()